"""Deterministic skill aliases for player-facing learning commands."""

SKILL_ALIASES = {
    "app": "appraisal",
    "appraisal": "appraisal",
    "arc": "arcana",
    "arcana": "arcana",
    "ath": "athletics",
    "athletics": "athletics",
    "att": "attunement",
    "attunement": "attunement",
    "backstab": "backstab",
    "blunt": "blunt",
    "brig": "brigandine",
    "brigandine": "brigandine",
    "brawl": "brawling",
    "brawling": "brawling",
    "chain": "chain_armor",
    "chain armor": "chain_armor",
    "combat": "combat",
    "debil": "debilitation",
    "debilitation": "debilitation",
    "disengage": "disengage",
    "empathy": "empathy",
    "eva": "evasion",
    "evasion": "evasion",
    "fa": "first_aid",
    "first aid": "first_aid",
    "he": "heavy_edge",
    "heavy edge": "heavy_edge",
    "heavy edged": "heavy_edge",
    "instinct": "instinct",
    "la": "light_armor",
    "light armor": "light_armor",
    "le": "light_edge",
    "light edge": "light_edge",
    "light edged": "light_edge",
    "light edged weapons": "light_edge",
    "lock": "locksmithing",
    "locksmithing": "locksmithing",
    "lockpicking": "locksmithing",
    "ml": "mechanical_lore",
    "mechanical lore": "mechanical_lore",
    "outdoors": "outdoorsmanship",
    "outdoorsmanship": "outdoorsmanship",
    "perc": "perception",
    "perception": "perception",
    "plate": "plate_armor",
    "plate armor": "plate_armor",
    "pole": "polearm",
    "polearm": "polearm",
    "sch": "scholarship",
    "scholarship": "scholarship",
    "skin": "skinning",
    "skinning": "skinning",
    "stealth": "stealth",
    "tact": "tactics",
    "tactics": "tactics",
    "theurgy": "theurgy",
    "tm": "targeted_magic",
    "targeted magic": "targeted_magic",
    "trade": "trading",
    "trading": "trading",
    "util": "utility",
    "utility": "utility",
    "aug": "augmentation",
    "augmentation": "augmentation",
    "ward": "warding",
    "warding": "warding",
    "than": "thanatology",
    "thanatology": "thanatology",
    "thief": "thievery",
    "thievery": "thievery",
    "moe": "multiple_engaged_opponent",
    "multiple engaged opponent": "multiple_engaged_opponent",
    "multiple opponents": "multiple_engaged_opponent",
    "parry": "parry_ability",
    "parry ability": "parry_ability",
    "shield": "shield_usage",
    "shield usage": "shield_usage",
}


def resolve_skill_alias(alias_input):
    if not alias_input:
        return None
    normalized = str(alias_input or "").strip().lower()
    return SKILL_ALIASES.get(normalized)


def list_aliases_for_skill(skill_id):
    normalized = str(skill_id or "").strip().lower()
    return sorted([alias for alias, resolved in SKILL_ALIASES.items() if resolved == normalized])