from .audit_service import (
    AUDIT_AVAILABLE,
    AUDIT_ENABLED,
    get_audit_by_action,
    get_audit_for_object,
    get_audit_in_range,
    get_audit_log_path,
    load_audit_log,
    log_audit_event,
)
from .diff_history_service import DIFF_HISTORY_AVAILABLE, append_history_entry, get_diff_history_path, load_history
from .exit_service import BUILDER_EXIT_SERVICE_AVAILABLE, create_exit, delete_exit, ensure_exit, find_exit, get_exit_by_id, update_exit
from .instance_service import INSTANCE_AVAILABLE, delete_instance, delete_instance_by_id, get_instance, require_instance, update_instance, update_instance_by_id
from .map_exporter import BUILDER_MAP_EXPORT_AVAILABLE, export_map
from .map_diff_service import DIFF_AVAILABLE, DiffApplyError, apply_diff, apply_operation
from .map_importer import import_map
from .placement_service import PLACEMENT_AVAILABLE, get_placement_info, move_instance, move_to_container, move_to_location, move_to_room, move_with_relation
from .room_service import BUILDER_ROOM_SERVICE_AVAILABLE, create_room, get_room, normalize_room, update_room
from .session_service import SESSION_AVAILABLE, create_session, get_session
from .spawn_service import (
    BUILDER_SPAWN_SERVICE_AVAILABLE,
    create_item_instance,
    create_npc_instance,
    spawn_from_template,
    spawn_from_template_result,
)
from .template_service import (
    BUILDER_TEMPLATE_SERVICE_AVAILABLE,
    get_template,
    list_templates,
    load_template_registry,
    register_template,
    require_template,
    save_template_registry,
    search_templates,
    update_template,
)
from .undo_service import UNDO_AVAILABLE, apply_redo, apply_undo, build_inverse_diff, capture_pre_state, invert_operation, is_operation_invertible
from .zone_service import BUILDER_ZONE_SERVICE_AVAILABLE, create_zone, get_zone, list_zones, load_zone_registry, require_zone, save_zone_registry

__all__ = [
    "AUDIT_AVAILABLE",
    "AUDIT_ENABLED",
    "BUILDER_EXIT_SERVICE_AVAILABLE",
    "BUILDER_MAP_EXPORT_AVAILABLE",
    "DIFF_AVAILABLE",
    "DIFF_HISTORY_AVAILABLE",
    "DiffApplyError",
    "INSTANCE_AVAILABLE",
    "BUILDER_ROOM_SERVICE_AVAILABLE",
    "BUILDER_SPAWN_SERVICE_AVAILABLE",
    "BUILDER_TEMPLATE_SERVICE_AVAILABLE",
    "BUILDER_ZONE_SERVICE_AVAILABLE",
    "PLACEMENT_AVAILABLE",
    "SESSION_AVAILABLE",
    "UNDO_AVAILABLE",
    "append_history_entry",
    "apply_diff",
    "apply_operation",
    "apply_redo",
    "apply_undo",
    "build_inverse_diff",
    "capture_pre_state",
    "create_exit",
    "create_item_instance",
    "create_npc_instance",
    "create_room",
    "create_session",
    "delete_exit",
    "delete_instance",
    "delete_instance_by_id",
    "ensure_exit",
    "export_map",
    "find_exit",
    "get_exit_by_id",
    "get_audit_by_action",
    "get_audit_for_object",
    "get_audit_in_range",
    "get_audit_log_path",
    "get_diff_history_path",
    "get_instance",
    "get_placement_info",
    "get_template",
    "get_zone",
    "get_room",
    "get_session",
    "import_map",
    "invert_operation",
    "is_operation_invertible",
    "list_templates",
    "list_zones",
    "load_zone_registry",
    "load_audit_log",
    "load_history",
    "load_template_registry",
    "log_audit_event",
    "move_to_container",
    "move_instance",
    "move_to_location",
    "move_to_room",
    "move_with_relation",
    "normalize_room",
    "register_template",
    "require_instance",
    "require_template",
    "save_template_registry",
    "save_zone_registry",
    "search_templates",
    "spawn_from_template",
    "spawn_from_template_result",
    "create_zone",
    "require_zone",
    "update_instance",
    "update_instance_by_id",
    "update_room",
    "update_exit",
    "update_template",
]