# RULE:
# This file contains DATA ONLY.
# No logic, no calculations, no service calls.

from dataclasses import dataclass, field


@dataclass(frozen=True, slots=True)
class Spell:
    id: str
    name: str
    abbr: str
    mana_type: str
    spell_type: str
    cast_style: str
    allowed_professions: list[str]
    min_circle: int
    min_skill: dict[str, int]
    safe_mana: int
    base_difficulty: int
    scaling: str
    spellbook: str
    acquisition_methods: list[str]
    slot_cost: int = 0
    apprentice_until_circle: int | None = None
    mana_min: int = 1
    mana_max: int = 0
    diff_per_extra_mana: int = 0
    target_type: str = "self"
    min_prep_time: int = 10
    expiry_window: int = 300
    canon_status: str = "prototype"
    provenance: str = "gsl_2004"
    flags: list[str] = field(default_factory=list)
    effect_profile: dict[str, object] = field(default_factory=dict)


SPELL_REGISTRY: dict[str, Spell] = {}

SPELLCASTING_PROFESSIONS = [
    "bard",
    "cleric",
    "empath",
    "moon_mage",
    "necromancer",
    "paladin",
    "ranger",
    "trader",
    "warrior_mage",
]

# DRG-EMPATH-04A repair decision: Repair-3.
# Canonical Empath healing is wound transfer first, then self-healing, so
# this live row remains an explicit hybrid_design exception rather than being
# silently rewritten into canonical behavior. The canonical self-heal path now
# lives in vitality_healing / heal_wounds / heal_scars below.
SPELL_REGISTRY["empath_heal"] = Spell(
    id="empath_heal",
    name="Heal",
    abbr="hl",
    mana_type="life",
    spell_type="healing",
    cast_style="standard",
    allowed_professions=["empath"],
    min_circle=1,
    min_skill={"primary_magic": 10},
    safe_mana=10,
    base_difficulty=20,
    scaling="linear",
    spellbook="Healing",
    acquisition_methods=["npc", "player"],
    target_type="single",
    provenance="hybrid_design",
)

# DRG-EMPATH-04A: Canonical 2004-GSL Empath Healing Book tier 1-2 rows.
SPELL_REGISTRY["vitality_healing"] = Spell(
    id="vitality_healing",
    name="Vitality Healing",
    abbr="vh",
    mana_type="life",
    spell_type="healing",
    cast_style="standard",
    allowed_professions=["empath"],
    min_circle=1,
    min_skill={"primary_magic": 10},
    safe_mana=1,
    mana_min=1,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=6,
    scaling="linear",
    spellbook="Healing",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    apprentice_until_circle=10,
    target_type="self",
    min_prep_time=3,
    expiry_window=120,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s02912"],
    effect_profile={
        "healing_mode": "hp",
        "gsl_spell_id": 401005,
        "castmod_a3": "050202003",
    },
)

SPELL_REGISTRY["heal_wounds"] = Spell(
    id="heal_wounds",
    name="Heal Wounds",
    abbr="hw",
    mana_type="life",
    spell_type="healing",
    cast_style="standard",
    allowed_professions=["empath"],
    min_circle=4,
    min_skill={"primary_magic": 20},
    safe_mana=13,
    mana_min=13,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=15,
    scaling="linear",
    spellbook="Healing",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    target_type="self",
    min_prep_time=5,
    expiry_window=120,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s05151"],
    effect_profile={
        "healing_mode": "empath_wounds",
        "gsl_spell_id": 401006,
        "castmod_a3": "070140005",
    },
)

SPELL_REGISTRY["heal_scars"] = Spell(
    id="heal_scars",
    name="Heal Scars",
    abbr="hs",
    mana_type="life",
    spell_type="healing",
    cast_style="standard",
    allowed_professions=["empath"],
    min_circle=6,
    min_skill={"primary_magic": 30},
    safe_mana=18,
    mana_min=18,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=18,
    scaling="linear",
    spellbook="Healing",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    target_type="self",
    min_prep_time=6,
    expiry_window=120,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s05152"],
    effect_profile={
        "healing_mode": "scars",
        "gsl_spell_id": 401007,
        "castmod_a3": "055180007",
    },
)

# DRG-EMPATH-04B: Canonical 2004-GSL Empath Healing Book tier 3-4 rows.
SPELL_REGISTRY["external_wound_healing"] = Spell(
    id="external_wound_healing",
    name="External Wound Healing",
    abbr="ewh",
    mana_type="life",
    spell_type="healing",
    cast_style="standard",
    allowed_professions=["empath"],
    min_circle=1,
    min_skill={"primary_magic": 10},
    safe_mana=1,
    mana_min=1,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=2,
    scaling="linear",
    spellbook="Healing",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    apprentice_until_circle=10,
    target_type="self",
    min_prep_time=2,
    expiry_window=120,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s00946"],
    effect_profile={
        "healing_mode": "external_wounds",
        "gsl_spell_id": 401001,
        "castmod_a3": "063155004",
    },
)

SPELL_REGISTRY["internal_wound_healing"] = Spell(
    id="internal_wound_healing",
    name="Internal Wound Healing",
    abbr="iwh",
    mana_type="life",
    spell_type="healing",
    cast_style="standard",
    allowed_professions=["empath"],
    min_circle=2,
    min_skill={"primary_magic": 15},
    safe_mana=6,
    mana_min=6,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=8,
    scaling="linear",
    spellbook="Healing",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    apprentice_until_circle=10,
    target_type="self",
    min_prep_time=3,
    expiry_window=120,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s01463"],
    effect_profile={
        "healing_mode": "internal_wounds",
        "gsl_spell_id": 401002,
        "castmod_a3": "063155004",
    },
)

SPELL_REGISTRY["heal"] = Spell(
    id="heal",
    name="Heal",
    abbr="hea",
    mana_type="life",
    spell_type="healing",
    cast_style="standard",
    allowed_professions=["empath"],
    min_circle=7,
    min_skill={"primary_magic": 40},
    safe_mana=13,
    mana_min=13,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=60,
    scaling="linear",
    spellbook="Healing",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    target_type="self",
    min_prep_time=7,
    expiry_window=120,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s09381"],
    effect_profile={
        "healing_mode": "combined_heal",
        "gsl_spell_id": 401008,
        "castmod_a3": "800140014",
    },
)

# DRG-EMPATH-05: Canonical 2004-GSL Empath Cleansing Book rows.
# Both scripts are self-cast only (`$OTHER` sets `$BREAK`). MVP ships only
# the general-purpose cleanse; per-poison/per-disease targeting defers.
SPELL_REGISTRY["flush_poisons"] = Spell(
    id="flush_poisons",
    name="Flush Poisons",
    abbr="fp",
    mana_type="life",
    spell_type="utility",
    cast_style="standard",
    allowed_professions=["empath"],
    min_circle=5,
    min_skill={"primary_magic": 25},
    safe_mana=10,
    mana_min=10,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=35,
    scaling="linear",
    spellbook="Cleansing",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    target_type="self",
    min_prep_time=5,
    expiry_window=120,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s02913", "specific_targeting_deferred"],
    effect_profile={
        "utility_behavior": "flush_poisons",
        "cleanse_condition": "poison",
        "gsl_spell_id": 402002,
        "castmod_a0": 10,
        "castmod_a1": 35,
        "castmod_a3": "100110004",
    },
)

SPELL_REGISTRY["cure_disease"] = Spell(
    id="cure_disease",
    name="Cure Disease",
    abbr="cd",
    mana_type="life",
    spell_type="utility",
    cast_style="standard",
    allowed_professions=["empath"],
    min_circle=6,
    min_skill={"primary_magic": 30},
    safe_mana=12,
    mana_min=12,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=20,
    scaling="linear",
    spellbook="Cleansing",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    target_type="self",
    min_prep_time=5,
    expiry_window=120,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s02914", "specific_targeting_deferred"],
    effect_profile={
        "utility_behavior": "cure_disease",
        "cleanse_condition": "disease",
        "gsl_spell_id": 402003,
        "castmod_a0": 12,
        "castmod_a1": 20,
        "castmod_a3": "100112004",
    },
)

# DRG-EMPATH-06: Canonical 2004-GSL Empath Vitality Book rows.
SPELL_REGISTRY["refresh"] = Spell(
    id="refresh",
    name="Refresh",
    abbr="ref",
    mana_type="life",
    spell_type="utility",
    cast_style="standard",
    allowed_professions=["empath"],
    min_circle=3,
    min_skill={"primary_magic": 18},
    safe_mana=1,
    mana_min=1,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=15,
    scaling="linear",
    spellbook="Vitality",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    apprentice_until_circle=10,
    target_type="self_or_other",
    min_prep_time=2,
    expiry_window=120,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s02915", "hybrid_instant_fatigue_reduction"],
    effect_profile={
        "utility_behavior": "refresh",
        "gsl_spell_id": 403001,
        "castmod_a0": 1,
        "castmod_a1": 15,
        "castmod_a3": "075133007",
        "other_target_scale": 0.75,
    },
)

SPELL_REGISTRY["raise_power"] = Spell(
    id="raise_power",
    name="Raise Power",
    abbr="rp",
    mana_type="life",
    spell_type="utility",
    cast_style="standard",
    allowed_professions=["empath"],
    min_circle=6,
    min_skill={"primary_magic": 28},
    safe_mana=6,
    mana_min=6,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=18,
    scaling="linear",
    spellbook="Vitality",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    target_type="self",
    min_prep_time=4,
    expiry_window=120,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s02916", "hybrid_room_mana_no_decay"],
    effect_profile={
        "utility_behavior": "raise_power",
        "gsl_spell_id": 403002,
        "castmod_a0": 6,
        "castmod_a1": 18,
        "castmod_a3": "036330004",
        "room_mana_boost_scale": 0.03,
        "group_member_bonus": 0.05,
    },
)

SPELL_REGISTRY["gift_of_life"] = Spell(
    id="gift_of_life",
    name="Gift of Life",
    abbr="gol",
    mana_type="life",
    spell_type="utility",
    cast_style="standard",
    allowed_professions=["empath"],
    min_circle=10,
    min_skill={"primary_magic": 45},
    safe_mana=6,
    mana_min=6,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=60,
    scaling="linear",
    spellbook="Vitality",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    target_type="self",
    min_prep_time=5,
    expiry_window=120,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s02917", "hybrid_saf_gate_deferred"],
    effect_profile={
        "utility_behavior": "gift_of_life",
        "gsl_spell_id": 403003,
        "castmod_a0": 6,
        "castmod_a1": 60,
        "castmod_a3": "080123007",
        "base_duration": 900,
        "duration_scale": 10.0,
        "capability_flag": "gift_of_life_active",
        "stamina_bonus": 8,
        "link_bonus": 2,
    },
)

# DRG-EMPATH-07: Canonical 2004-GSL Empath Protection Book rows.
# Innocence reuses existing NPC threat/target state and a short-lived
# innocence-active flag rather than introducing a new Will-vs-Will subsystem.
SPELL_REGISTRY["innocence"] = Spell(
    id="innocence",
    name="Innocence",
    abbr="ino",
    mana_type="life",
    spell_type="utility",
    cast_style="standard",
    allowed_professions=["empath"],
    min_circle=8,
    min_skill={"primary_magic": 32},
    safe_mana=5,
    mana_min=5,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=25,
    scaling="linear",
    spellbook="Protection",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    target_type="self",
    min_prep_time=4,
    expiry_window=120,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s02918", "hybrid_existing_npc_aggro_seam"],
    effect_profile={
        "utility_behavior": "innocence",
        "gsl_spell_id": 404002,
        "castmod_a0": 5,
        "castmod_a1": 25,
        "castmod_a3": "057190008",
        "base_duration": 20,
        "duration_scale": 0.5,
        "capability_flag": "innocence_active",
        "undead_backfire_threat": 25,
    },
)

# DRG-EMPATH-07: Zone of Protection is canonically self-cast, but the current
# bounded group seam is the existing room-account helper rather than a follow-party model.
SPELL_REGISTRY["zone_of_protection"] = Spell(
    id="zone_of_protection",
    name="Zone of Protection",
    abbr="zop",
    mana_type="life",
    spell_type="warding",
    cast_style="standard",
    allowed_professions=["empath"],
    min_circle=11,
    min_skill={"primary_magic": 50},
    safe_mana=15,
    mana_min=15,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=40,
    scaling="linear",
    spellbook="Protection",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    target_type="self",
    min_prep_time=5,
    expiry_window=120,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s03365", "hybrid_room_account_group_slice"],
    effect_profile={
        "gsl_spell_id": 404003,
        "castmod_a0": 15,
        "castmod_a1": 40,
        "castmod_a3": "050015010",
        "base_strength": 10,
        "strength_scale": 0.45,
        "base_duration": 180,
        "duration_scale": 4.0,
        "group_from_caster": True,
    },
)

# DRG-RANGER-02-ANIMAL: Canonical 2004-GSL Ranger Animal Abilities Book rows.
# Step 0 classification: B. Raw CASTMOD and targeting were verified directly from
# DireLore, but several rows had to be resolved by script name because the raw
# spell index is incomplete for 405004-405010.
SPELL_REGISTRY["wolf_scent"] = Spell(
    id="wolf_scent",
    name="Wolf Scent",
    abbr="ws",
    mana_type="life",
    spell_type="utility",
    cast_style="standard",
    allowed_professions=["ranger"],
    min_circle=1,
    min_skill={"primary_magic": 10},
    safe_mana=5,
    mana_min=5,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=6,
    scaling="linear",
    spellbook="Animal Abilities",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    apprentice_until_circle=10,
    target_type="self_or_other",
    min_prep_time=3,
    expiry_window=300,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s03366"],
    effect_profile={
        "utility_behavior": "ranger_boon",
        "effect_type": "wolf_scent",
        "capability_flag": "wolf_scent_active",
        "gsl_spell_id": 405001,
        "castmod_a0": 5,
        "castmod_a1": 6,
        "castmod_a3": "060182006",
    },
)

SPELL_REGISTRY["see_the_wind"] = Spell(
    id="see_the_wind",
    name="See the Wind",
    abbr="stw",
    mana_type="life",
    spell_type="augmentation",
    cast_style="standard",
    allowed_professions=["ranger"],
    min_circle=2,
    min_skill={"primary_magic": 15},
    safe_mana=5,
    mana_min=5,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=2,
    scaling="linear",
    spellbook="Animal Abilities",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    apprentice_until_circle=10,
    target_type="self_or_other",
    min_prep_time=3,
    expiry_window=300,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s03367"],
    effect_profile={
        "gsl_spell_id": 405002,
        "castmod_a0": 5,
        "castmod_a1": 2,
        "castmod_a3": "060182003",
        "contest_modifiers": {
            "accuracy": 0.35,
        },
    },
)

SPELL_REGISTRY["spider_climb"] = Spell(
    id="spider_climb",
    name="Spider Climb",
    abbr="spc",
    mana_type="life",
    spell_type="utility",
    cast_style="standard",
    allowed_professions=["ranger"],
    min_circle=3,
    min_skill={"primary_magic": 20},
    safe_mana=8,
    mana_min=8,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=8,
    scaling="linear",
    spellbook="Animal Abilities",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    apprentice_until_circle=10,
    target_type="self_or_other",
    min_prep_time=4,
    expiry_window=300,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s03368"],
    effect_profile={
        "utility_behavior": "ranger_boon",
        "effect_type": "spider_climb",
        "capability_flag": "spider_climb_active",
        "gsl_spell_id": 405003,
        "castmod_a0": 8,
        "castmod_a1": 8,
        "castmod_a3": "063182005",
    },
)

SPELL_REGISTRY["eagle_vision"] = Spell(
    id="eagle_vision",
    name="Eagle Vision",
    abbr="ev",
    mana_type="life",
    spell_type="utility",
    cast_style="standard",
    allowed_professions=["ranger"],
    min_circle=4,
    min_skill={"primary_magic": 25},
    safe_mana=18,
    mana_min=18,
    mana_max=100,
    diff_per_extra_mana=1,
    base_difficulty=55,
    scaling="linear",
    spellbook="Animal Abilities",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    target_type="self",
    min_prep_time=5,
    expiry_window=300,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s03369", "resolved_via_script_name"],
    effect_profile={
        "utility_behavior": "ranger_boon",
        "effect_type": "eagle_vision",
        "capability_flag": "eagle_vision_active",
        "gsl_spell_id": 405004,
        "castmod_a0": 18,
        "castmod_a1": 55,
        "castmod_a3": "500001001",
    },
)

SPELL_REGISTRY["cheetah_swiftness"] = Spell(
    id="cheetah_swiftness",
    name="Cheetah Swiftness",
    abbr="cs",
    mana_type="life",
    spell_type="augmentation",
    cast_style="standard",
    allowed_professions=["ranger"],
    min_circle=5,
    min_skill={"primary_magic": 30},
    safe_mana=5,
    mana_min=5,
    mana_max=100,
    diff_per_extra_mana=35,
    base_difficulty=15,
    scaling="linear",
    spellbook="Animal Abilities",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    target_type="self",
    min_prep_time=5,
    expiry_window=300,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s05344", "resolved_via_script_name", "cyclic_surface_deferred"],
    effect_profile={
        "gsl_spell_id": 405005,
        "castmod_a0": 5,
        "castmod_a1": 15,
        "castmod_a3": "200020035",
        "contest_modifiers": {
            "evasion": 0.4,
        },
    },
)

SPELL_REGISTRY["bear_strength"] = Spell(
    id="bear_strength",
    name="Bear Strength",
    abbr="bs",
    mana_type="life",
    spell_type="augmentation",
    cast_style="standard",
    allowed_professions=["ranger"],
    min_circle=6,
    min_skill={"primary_magic": 35},
    safe_mana=10,
    mana_min=10,
    mana_max=100,
    diff_per_extra_mana=50,
    base_difficulty=30,
    scaling="linear",
    spellbook="Animal Abilities",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    target_type="self",
    min_prep_time=6,
    expiry_window=300,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s08110", "resolved_via_script_name", "cyclic_surface_deferred"],
    effect_profile={
        "gsl_spell_id": 405006,
        "castmod_a0": 10,
        "castmod_a1": 30,
        "castmod_a3": "200020050",
        "contest_modifiers": {
            "accuracy": 0.45,
        },
    },
)

SPELL_REGISTRY["caiman_swim"] = Spell(
    id="caiman_swim",
    name="Caiman Swim",
    abbr="cas",
    mana_type="life",
    spell_type="utility",
    cast_style="standard",
    allowed_professions=["ranger"],
    min_circle=7,
    min_skill={"primary_magic": 40},
    safe_mana=8,
    mana_min=8,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=8,
    scaling="linear",
    spellbook="Animal Abilities",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    target_type="self_or_other",
    min_prep_time=6,
    expiry_window=300,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s08104"],
    effect_profile={
        "utility_behavior": "ranger_boon",
        "effect_type": "caiman_swim",
        "capability_flag": "caiman_swim_active",
        "gsl_spell_id": 405007,
        "castmod_a0": 8,
        "castmod_a1": 8,
        "castmod_a3": "063182005",
    },
)

SPELL_REGISTRY["grizzly_claw"] = Spell(
    id="grizzly_claw",
    name="Grizzly Claw",
    abbr="gc",
    mana_type="life",
    spell_type="augmentation",
    cast_style="standard",
    allowed_professions=["ranger"],
    min_circle=8,
    min_skill={"primary_magic": 45},
    safe_mana=12,
    mana_min=12,
    mana_max=100,
    diff_per_extra_mana=10,
    base_difficulty=8,
    scaling="linear",
    spellbook="Animal Abilities",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    target_type="single",
    min_prep_time=7,
    expiry_window=300,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s11243", "resolved_via_script_name", "promoted_name_diverges"],
    effect_profile={
        "gsl_spell_id": 405008,
        "castmod_a0": 12,
        "castmod_a1": 8,
        "castmod_a3": "060180010",
        "disallow_self_target": True,
        "contest_modifiers": {
            "accuracy": 0.35,
        },
    },
)

SPELL_REGISTRY["senses_of_the_tiger"] = Spell(
    id="senses_of_the_tiger",
    name="Senses of the Tiger",
    abbr="sot",
    mana_type="life",
    spell_type="augmentation",
    cast_style="standard",
    allowed_professions=["ranger"],
    min_circle=9,
    min_skill={"primary_magic": 50},
    safe_mana=5,
    mana_min=5,
    mana_max=100,
    diff_per_extra_mana=7,
    base_difficulty=2,
    scaling="linear",
    spellbook="Animal Abilities",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    target_type="self",
    min_prep_time=7,
    expiry_window=300,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s11242", "resolved_via_script_name"],
    effect_profile={
        "gsl_spell_id": 405009,
        "castmod_a0": 5,
        "castmod_a1": 2,
        "castmod_a3": "060180007",
        "contest_modifiers": {
            "accuracy": 0.2,
            "evasion": 0.2,
        },
    },
)

SPELL_REGISTRY["wisdom_of_the_pack"] = Spell(
    id="wisdom_of_the_pack",
    name="Wisdom of the Pack",
    abbr="wotp",
    mana_type="life",
    spell_type="utility",
    cast_style="standard",
    allowed_professions=["ranger"],
    min_circle=10,
    min_skill={"primary_magic": 55},
    safe_mana=8,
    mana_min=8,
    mana_max=100,
    diff_per_extra_mana=16,
    base_difficulty=25,
    scaling="linear",
    spellbook="Animal Abilities",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    target_type="self",
    min_prep_time=8,
    expiry_window=300,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s12148", "resolved_via_script_name", "wolf_scent_prereq_documented"],
    effect_profile={
        "utility_behavior": "ranger_boon",
        "effect_type": "wisdom_of_the_pack",
        "capability_flag": "wisdom_of_the_pack_active",
        "gsl_spell_id": 405010,
        "castmod_a0": 8,
        "castmod_a1": 25,
        "castmod_a3": "050200016",
        "prerequisite_spell": "wolf_scent",
    },
)

# DRG-RANGER-03-SURVIVAL: Canonical 2004-GSL Ranger Wilderness Survival Book rows.
# Step 0 classification: B. DireLore confirms the spellbook roster and CASTMOD data,
# but Earth Meld, Breathe Water, and Water Purification required script-name fallback
# because the promoted spell index is incomplete or mismatched for those entries.
SPELL_REGISTRY["hands_of_lirisa"] = Spell(
    id="hands_of_lirisa",
    name="Hands of Lirisa",
    abbr="hol",
    mana_type="life",
    spell_type="utility",
    cast_style="standard",
    allowed_professions=["ranger"],
    min_circle=1,
    min_skill={"primary_magic": 10},
    safe_mana=3,
    mana_min=3,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=2,
    scaling="linear",
    spellbook="Wilderness Survival",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    apprentice_until_circle=10,
    target_type="self_or_other",
    min_prep_time=3,
    expiry_window=300,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s03370"],
    effect_profile={
        "utility_behavior": "ranger_boon",
        "effect_type": "hands_of_lirisa",
        "capability_flag": "hands_of_lirisa_active",
        "gsl_spell_id": 406001,
        "castmod_a0": 3,
        "castmod_a1": 2,
        "castmod_a3": "064167002",
    },
)

SPELL_REGISTRY["earth_meld"] = Spell(
    id="earth_meld",
    name="Earth Meld",
    abbr="em",
    mana_type="life",
    spell_type="utility",
    cast_style="standard",
    allowed_professions=["ranger"],
    min_circle=2,
    min_skill={"primary_magic": 15},
    safe_mana=8,
    mana_min=8,
    mana_max=100,
    diff_per_extra_mana=5,
    base_difficulty=6,
    scaling="linear",
    spellbook="Wilderness Survival",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    apprentice_until_circle=10,
    target_type="self_or_other",
    min_prep_time=3,
    expiry_window=300,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s03371", "resolved_via_script_name", "ranger_saf_gate_1_reference"],
    effect_profile={
        "utility_behavior": "ranger_boon",
        "effect_type": "earth_meld",
        "capability_flag": "earth_meld_active",
        "gsl_spell_id": 406002,
        "castmod_a0": 8,
        "castmod_a1": 6,
        "castmod_a3": "063182005",
    },
)

SPELL_REGISTRY["mesmerize"] = Spell(
    id="mesmerize",
    name="Mesmerize",
    abbr="mez",
    mana_type="life",
    spell_type="debilitation",
    cast_style="standard",
    allowed_professions=["ranger"],
    min_circle=3,
    min_skill={"primary_magic": 20},
    safe_mana=13,
    mana_min=13,
    mana_max=100,
    diff_per_extra_mana=18,
    base_difficulty=35,
    scaling="linear",
    spellbook="Wilderness Survival",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    apprentice_until_circle=10,
    target_type="single",
    min_prep_time=4,
    expiry_window=120,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s03372", "resolved_via_script_name", "effect_code_mismatch"],
    effect_profile={
        "gsl_spell_id": 406003,
        "castmod_a0": 13,
        "castmod_a1": 35,
        "castmod_a3": "500012018",
        "effect_type": "mesmerize",
        "base_strength": 1.0,
        "strength_scale": 0.04,
        "base_duration": 6.0,
        "duration_scale": 1.0,
    },
)

SPELL_REGISTRY["blend"] = Spell(
    id="blend",
    name="Blend",
    abbr="bl",
    mana_type="life",
    spell_type="utility",
    cast_style="standard",
    allowed_professions=["ranger"],
    min_circle=4,
    min_skill={"primary_magic": 25},
    safe_mana=12,
    mana_min=12,
    mana_max=100,
    diff_per_extra_mana=17,
    base_difficulty=10,
    scaling="linear",
    spellbook="Wilderness Survival",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    apprentice_until_circle=10,
    target_type="self",
    min_prep_time=4,
    expiry_window=300,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s04972", "resolved_via_script_name"],
    effect_profile={
        "utility_behavior": "ranger_boon",
        "effect_type": "blend",
        "capability_flag": "blend_active",
        "gsl_spell_id": 406004,
        "castmod_a0": 12,
        "castmod_a1": 10,
        "castmod_a3": "013999017",
    },
)

SPELL_REGISTRY["breathe_water"] = Spell(
    id="breathe_water",
    name="Breathe Water",
    abbr="bw",
    mana_type="life",
    spell_type="utility",
    cast_style="standard",
    allowed_professions=["ranger"],
    min_circle=5,
    min_skill={"primary_magic": 30},
    safe_mana=24,
    mana_min=24,
    mana_max=100,
    diff_per_extra_mana=14,
    base_difficulty=99,
    scaling="linear",
    spellbook="Wilderness Survival",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    apprentice_until_circle=10,
    target_type="self",
    min_prep_time=5,
    expiry_window=300,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s06440", "resolved_via_script_name"],
    effect_profile={
        "utility_behavior": "ranger_boon",
        "effect_type": "breathe_water",
        "capability_flag": "breathe_water_active",
        "gsl_spell_id": 406005,
        "castmod_a0": 24,
        "castmod_a1": 99,
        "castmod_a3": "200001014",
    },
)

SPELL_REGISTRY["water_purification"] = Spell(
    id="water_purification",
    name="Water Purification",
    abbr="wp",
    mana_type="life",
    spell_type="utility",
    cast_style="standard",
    allowed_professions=["ranger"],
    min_circle=6,
    min_skill={"primary_magic": 35},
    safe_mana=4,
    mana_min=4,
    mana_max=100,
    diff_per_extra_mana=18,
    base_difficulty=27,
    scaling="linear",
    spellbook="Wilderness Survival",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    apprentice_until_circle=10,
    target_type="self",
    min_prep_time=5,
    expiry_window=300,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s05692", "resolved_via_script_name"],
    effect_profile={
        "utility_behavior": "water_purification",
        "effect_type": "water_purification",
        "capability_flag": "water_purification_active",
        "gsl_spell_id": 406006,
        "castmod_a0": 4,
        "castmod_a1": 27,
        "castmod_a3": "150015018",
        "base_duration": 120,
        "duration_scale": 3.0,
    },
)

# DRG-RANGER-04-DEFENSE: Canonical 2004-GSL Ranger Wilderness Defense Book rows.
# Step 0 classification: B. DireLore confirms the 7-spell book and Gap 2 absence,
# but Compost, Swarm, Awaken Forest, and Hobble require script-number fallback,
# Harawep's Bonds surfaces promoted effect_code 1 instead of 407003, and Plague of
# Scavengers resolves from the promoted Ranger variant name.
SPELL_REGISTRY["compost"] = Spell(
    id="compost",
    name="Compost",
    abbr="com",
    mana_type="life",
    spell_type="utility",
    cast_style="standard",
    allowed_professions=["ranger"],
    min_circle=4,
    min_skill={"primary_magic": 25},
    safe_mana=10,
    mana_min=10,
    mana_max=100,
    diff_per_extra_mana=3,
    base_difficulty=1,
    scaling="linear",
    spellbook="Wilderness Defense",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    apprentice_until_circle=10,
    target_type="self",
    min_prep_time=4,
    expiry_window=180,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s03373", "resolved_via_script_number"],
    effect_profile={
        "utility_behavior": "ranger_room_effect",
        "effect_type": "compost",
        "room_state_key": "compost",
        "capability_flag": "compost_active",
        "gsl_spell_id": 407001,
        "castmod_a0": 10,
        "castmod_a1": 1,
        "castmod_a3": "050247003",
        "base_duration": 90,
        "duration_scale": 2.0,
    },
)

SPELL_REGISTRY["swarm"] = Spell(
    id="swarm",
    name="Swarm",
    abbr="swa",
    mana_type="life",
    spell_type="utility",
    cast_style="standard",
    allowed_professions=["ranger"],
    min_circle=5,
    min_skill={"primary_magic": 30},
    safe_mana=8,
    mana_min=8,
    mana_max=100,
    diff_per_extra_mana=11,
    base_difficulty=12,
    scaling="linear",
    spellbook="Wilderness Defense",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    apprentice_until_circle=10,
    target_type="single",
    min_prep_time=4,
    expiry_window=180,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s03374", "resolved_via_script_number"],
    effect_profile={
        "utility_behavior": "ranger_room_effect",
        "effect_type": "swarm",
        "room_state_key": "swarm",
        "capability_flag": "swarm_active",
        "disallow_self_target": True,
        "gsl_spell_id": 407002,
        "castmod_a0": 8,
        "castmod_a1": 12,
        "castmod_a3": "061185011",
        "base_duration": 60,
        "duration_scale": 2.0,
    },
)

SPELL_REGISTRY["haraweps_bonds"] = Spell(
    id="haraweps_bonds",
    name="Harawep's Bonds",
    abbr="hb",
    mana_type="life",
    spell_type="debilitation",
    cast_style="standard",
    allowed_professions=["ranger"],
    min_circle=6,
    min_skill={"primary_magic": 35},
    safe_mana=8,
    mana_min=8,
    mana_max=100,
    diff_per_extra_mana=15,
    base_difficulty=30,
    scaling="linear",
    spellbook="Wilderness Defense",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    apprentice_until_circle=10,
    target_type="single",
    min_prep_time=4,
    expiry_window=180,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s03375", "resolved_via_script_number", "effect_code_mismatch"],
    effect_profile={
        "gsl_spell_id": 407003,
        "castmod_a0": 8,
        "castmod_a1": 30,
        "castmod_a3": "060190015",
        "effect_type": "haraweps_bonds",
        "disallow_self_target": True,
        "base_strength": 1.0,
        "strength_scale": 0.05,
        "base_duration": 8.0,
        "duration_scale": 1.5,
        "contest_modifiers": {"evasion": 1.0},
        "encumbrance_modifier": 6,
    },
)

SPELL_REGISTRY["awaken_forest"] = Spell(
    id="awaken_forest",
    name="Awaken Forest",
    abbr="af",
    mana_type="life",
    spell_type="utility",
    cast_style="standard",
    allowed_professions=["ranger"],
    min_circle=7,
    min_skill={"primary_magic": 40},
    safe_mana=20,
    mana_min=20,
    mana_max=100,
    diff_per_extra_mana=20,
    base_difficulty=80,
    scaling="linear",
    spellbook="Wilderness Defense",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    apprentice_until_circle=10,
    target_type="self",
    min_prep_time=5,
    expiry_window=180,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s03376", "resolved_via_script_number"],
    effect_profile={
        "utility_behavior": "ranger_room_effect",
        "effect_type": "awaken_forest",
        "room_state_key": "awaken_forest",
        "capability_flag": "awaken_forest_active",
        "gsl_spell_id": 407004,
        "castmod_a0": 20,
        "castmod_a1": 80,
        "castmod_a3": "500010020",
        "base_duration": 75,
        "duration_scale": 1.5,
    },
)

SPELL_REGISTRY["hobble"] = Spell(
    id="hobble",
    name="Hobble",
    abbr="hob",
    mana_type="life",
    spell_type="debilitation",
    cast_style="standard",
    allowed_professions=["ranger"],
    min_circle=8,
    min_skill={"primary_magic": 45},
    safe_mana=9,
    mana_min=9,
    mana_max=100,
    diff_per_extra_mana=15,
    base_difficulty=65,
    scaling="linear",
    spellbook="Wilderness Defense",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    apprentice_until_circle=10,
    target_type="single",
    min_prep_time=5,
    expiry_window=180,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s06464", "resolved_via_script_number"],
    effect_profile={
        "gsl_spell_id": 407005,
        "castmod_a0": 9,
        "castmod_a1": 65,
        "castmod_a3": "500015015",
        "effect_type": "hobble",
        "disallow_self_target": True,
        "base_strength": 1.0,
        "strength_scale": 0.04,
        "base_duration": 7.0,
        "duration_scale": 1.5,
        "contest_modifiers": {"evasion": 1.0},
        "encumbrance_modifier": 4,
    },
)

SPELL_REGISTRY["branch_break"] = Spell(
    id="branch_break",
    name="Branch Break",
    abbr="bb",
    mana_type="life",
    spell_type="debilitation",
    cast_style="standard",
    allowed_professions=["ranger"],
    min_circle=9,
    min_skill={"primary_magic": 50},
    safe_mana=6,
    mana_min=6,
    mana_max=100,
    diff_per_extra_mana=8,
    base_difficulty=45,
    scaling="linear",
    spellbook="Wilderness Defense",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    apprentice_until_circle=10,
    target_type="single",
    min_prep_time=4,
    expiry_window=180,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s10271"],
    effect_profile={
        "gsl_spell_id": 407006,
        "castmod_a0": 6,
        "castmod_a1": 45,
        "castmod_a3": "60183008",
        "effect_type": "branch_break",
        "disallow_self_target": True,
        "base_strength": 1.0,
        "strength_scale": 0.05,
        "base_duration": 5.0,
        "duration_scale": 1.0,
        "damage_base": 4,
        "damage_scale": 2,
    },
)

SPELL_REGISTRY["plague_of_scavengers"] = Spell(
    id="plague_of_scavengers",
    name="Plague of Scavengers",
    abbr="pos",
    mana_type="life",
    spell_type="utility",
    cast_style="standard",
    allowed_professions=["ranger"],
    min_circle=10,
    min_skill={"primary_magic": 55},
    safe_mana=10,
    mana_min=10,
    mana_max=100,
    diff_per_extra_mana=16,
    base_difficulty=50,
    scaling="linear",
    spellbook="Wilderness Defense",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    apprentice_until_circle=10,
    target_type="single",
    min_prep_time=5,
    expiry_window=180,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s10011", "resolved_via_promoted_name_variant"],
    effect_profile={
        "utility_behavior": "ranger_room_effect",
        "effect_type": "plague_of_scavengers",
        "room_state_key": "plague_of_scavengers",
        "capability_flag": "plague_of_scavengers_active",
        "disallow_self_target": True,
        "gsl_spell_id": 407010,
        "castmod_a0": 10,
        "castmod_a1": 50,
        "castmod_a3": "062190016",
        "alternate_castmod_a0": 12,
        "alternate_castmod_a3": "062190011",
        "base_duration": 60,
        "duration_scale": 2.0,
    },
)

# DRG-CLERIC-02: Grandfathered as project-canonical per DRG-CANON-POLICY-001.
# Existing bespoke DireEngine Cleric spell, not 2004-GSL 206xxx content.
SPELL_REGISTRY["cleric_minor_heal"] = Spell(
    id="cleric_minor_heal",
    name="Minor Heal",
    abbr="mh",
    mana_type="holy",
    spell_type="healing",
    cast_style="standard",
    allowed_professions=["cleric"],
    min_circle=1,
    min_skill={"primary_magic": 10},
    safe_mana=10,
    base_difficulty=20,
    scaling="linear",
    spellbook="Spirit Manipulation",
    acquisition_methods=["npc", "player", "book"],
    target_type="single",
    provenance="directengine_canon",
)

# DRG-CLERIC-02: Grandfathered as project-canonical per DRG-CANON-POLICY-001.
# Existing Cleric-accessible DireEngine roster entry, not 2004-GSL 206xxx content.
SPELL_REGISTRY["bolster"] = Spell(
    id="bolster",
    name="Bolster",
    abbr="bol",
    mana_type="elemental",
    spell_type="augmentation",
    cast_style="standard",
    allowed_professions=list(SPELLCASTING_PROFESSIONS),
    min_circle=1,
    min_skill={"primary_magic": 10},
    safe_mana=10,
    base_difficulty=18,
    scaling="linear",
    spellbook="Fundamentals",
    acquisition_methods=["npc", "player", "book"],
    provenance="directengine_canon",
    effect_profile={
        "contest_modifiers": {
            "magic_attack": 1.0,
            "magic_defense": 1.0,
        },
    },
)

# DRG-CLERIC-02: Grandfathered as project-canonical per DRG-CANON-POLICY-001.
# Existing bespoke DireEngine Cleric spell, not 2004-GSL 206xxx content.
SPELL_REGISTRY["minor_barrier"] = Spell(
    id="minor_barrier",
    name="Minor Barrier",
    abbr="mb",
    mana_type="holy",
    spell_type="warding",
    cast_style="standard",
    allowed_professions=["cleric"],
    min_circle=3,
    min_skill={"primary_magic": 20},
    safe_mana=12,
    base_difficulty=25,
    scaling="linear",
    spellbook="Holy Defense",
    acquisition_methods=["npc", "player", "book"],
    provenance="directengine_canon",
)

# DRG-CLERIC-04: Canonical 2004-GSL Cleric blessing/buff additions.
SPELL_REGISTRY["bless"] = Spell(
    id="bless",
    name="Bless",
    abbr="bls",
    mana_type="holy",
    spell_type="utility",
    cast_style="standard",
    allowed_professions=["cleric"],
    min_circle=1,
    min_skill={"primary_magic": 10},
    safe_mana=10,
    mana_min=1,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=3,
    scaling="linear",
    spellbook="Holy Evocations",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    apprentice_until_circle=10,
    target_type="single",
    min_prep_time=3,
    expiry_window=600,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s01664"],
    effect_profile={
        "effect_type": "bless",
        "base_duration": 600,
        "duration_scale": 18.0,
        "capability_flag": "bless_active",
        "undead_accuracy_bonus_scale": 2.0,
        "undead_damage_bonus_scale": 1.0,
    },
)

SPELL_REGISTRY["protection_from_evil"] = Spell(
    id="protection_from_evil",
    name="Protection from Evil",
    abbr="pfe",
    mana_type="holy",
    spell_type="warding",
    cast_style="standard",
    allowed_professions=["cleric"],
    min_circle=3,
    min_skill={"primary_magic": 20},
    safe_mana=20,
    mana_min=5,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=1,
    scaling="linear",
    spellbook="Holy Defense",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    apprentice_until_circle=10,
    target_type="single",
    min_prep_time=4,
    expiry_window=600,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s00219"],
    effect_profile={
        "contest_modifiers": {
            "magic_defense": 1.0,
            "evasion": 0.5,
        },
        "undead_evasion_bonus_scale": 2.0,
    },
)

SPELL_REGISTRY["minor_physical_protection"] = Spell(
    id="minor_physical_protection",
    name="Minor Physical Protection",
    abbr="mpp",
    mana_type="holy",
    spell_type="warding",
    cast_style="standard",
    allowed_professions=["cleric"],
    min_circle=1,
    min_skill={"primary_magic": 10},
    safe_mana=15,
    mana_min=1,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=5,
    scaling="linear",
    spellbook="Holy Defense",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    target_type="self",
    min_prep_time=3,
    expiry_window=600,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s00952"],
    effect_profile={
        "absorbs_physical": True,
    },
)

SPELL_REGISTRY["major_physical_protection"] = Spell(
    id="major_physical_protection",
    name="Major Physical Protection",
    abbr="majp",
    mana_type="holy",
    spell_type="warding",
    cast_style="standard",
    allowed_professions=["cleric"],
    min_circle=5,
    min_skill={"primary_magic": 20},
    safe_mana=15,
    mana_min=15,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=55,
    scaling="linear",
    spellbook="Holy Defense",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    target_type="self",
    min_prep_time=5,
    expiry_window=600,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s06360"],
    effect_profile={
        "absorbs_physical": True,
        "strength_multiplier": 2.0,
    },
)

SPELL_REGISTRY["halo"] = Spell(
    id="halo",
    name="Halo",
    abbr="halo",
    mana_type="holy",
    spell_type="warding",
    cast_style="standard",
    allowed_professions=["cleric"],
    min_circle=20,
    min_skill={"primary_magic": 250},
    safe_mana=12,
    mana_min=12,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=75,
    scaling="linear",
    spellbook="Holy Defense",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=3,
    target_type="self",
    min_prep_time=30,
    expiry_window=600,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s08164", "pulse_mechanic_deferred"],
    effect_profile={
        "contest_modifiers": {
            "magic_defense": 1.0,
            "evasion": 1.0,
        },
        "undead_evasion_bonus_scale": 2.0,
        "strength_multiplier": 2.0,
    },
)

SPELL_REGISTRY["holy_light"] = Spell(
    id="holy_light",
    name="Holy Light",
    abbr="hol",
    mana_type="holy",
    spell_type="utility",
    cast_style="standard",
    allowed_professions=["cleric"],
    min_circle=2,
    min_skill={"primary_magic": 10},
    safe_mana=5,
    mana_min=1,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=2,
    scaling="linear",
    spellbook="Holy Evocations",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    apprentice_until_circle=10,
    target_type="self",
    min_prep_time=3,
    expiry_window=300,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s00950", "prep_floor_inferred_from_public_metadata"],
    effect_profile={
        "effect_type": "light",
        "base_duration": 300,
        "duration_scale": 12.0,
    },
)

SPELL_REGISTRY["divine_radiance"] = Spell(
    id="divine_radiance",
    name="Divine Radiance",
    abbr="dr",
    mana_type="holy",
    spell_type="warding",
    cast_style="standard",
    allowed_professions=["cleric"],
    min_circle=2,
    min_skill={"primary_magic": 10},
    safe_mana=1,
    mana_min=1,
    mana_max=50,
    diff_per_extra_mana=2,
    base_difficulty=18,
    scaling="linear",
    spellbook="Holy Evocations",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=3,
    target_type="self",
    min_prep_time=2,
    expiry_window=600,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s04171"],
    effect_profile={
        "contest_modifiers": {
            "magic_defense": 0.5,
            "evasion": 0.25,
        },
        "undead_evasion_bonus_scale": 1.0,
        "emits_light": True,
    },
)

SPELL_REGISTRY["rejuvenation"] = Spell(
    id="rejuvenation",
    name="Rejuvenation",
    abbr="rej",
    mana_type="holy",
    spell_type="resurrection",
    cast_style="standard",
    allowed_professions=["cleric"],
    min_circle=1,
    min_skill={"primary_magic": 10},
    safe_mana=5,
    mana_min=5,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=10,
    scaling="linear",
    spellbook="Spirit Manipulation",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    target_type="single",
    min_prep_time=5,
    expiry_window=300,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s02237"],
    effect_profile={
        "resurrection_behavior": "single_target_revive",
    },
)

SPELL_REGISTRY["mass_rejuvenation"] = Spell(
    id="mass_rejuvenation",
    name="Mass Rejuvenation",
    abbr="mre",
    mana_type="holy",
    spell_type="resurrection",
    cast_style="standard",
    allowed_professions=["cleric"],
    min_circle=10,
    min_skill={"primary_magic": 80},
    safe_mana=12,
    mana_min=12,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=150,
    scaling="linear",
    spellbook="Spirit Manipulation",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    target_type="room",
    min_prep_time=15,
    expiry_window=600,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s09118", "held_mana_ritual_deferred"],
    effect_profile={
        "resurrection_behavior": "deferred_held_mana_ritual_placeholder",
    },
)

SPELL_REGISTRY["aesrela_everild"] = Spell(
    id="aesrela_everild",
    name="Aesrela Everild",
    abbr="ae",
    mana_type="holy",
    spell_type="targeted_magic",
    cast_style="targeted",
    allowed_professions=["cleric"],
    min_circle=8,
    min_skill={"primary_magic": 60},
    safe_mana=20,
    mana_min=20,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=80,
    scaling="linear",
    spellbook="Divine Intervention",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    target_type="single",
    min_prep_time=10,
    expiry_window=300,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s04463"],
    effect_profile={
        "contest_primary_skill": "theurgy",
        "contest_defense_skill": "targeted_magic",
        "contest_defense_stat": "reflex",
        "damage_components": [("fire", 3)],
        "on_hit_stun": True,
    },
)

SPELL_REGISTRY["revelation"] = Spell(
    id="revelation",
    name="Revelation",
    abbr="rev",
    mana_type="holy",
    spell_type="utility",
    cast_style="targeted",
    allowed_professions=["cleric"],
    min_circle=6,
    min_skill={"primary_magic": 40},
    safe_mana=9,
    mana_min=9,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=55,
    scaling="linear",
    spellbook="Divine Intervention",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    target_type="single",
    min_prep_time=5,
    expiry_window=180,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s07085"],
    effect_profile={
        "effect_type": "revelation",
        "utility_behavior": "revelation",
    },
)

SPELL_REGISTRY["spirit_beacon"] = Spell(
    id="spirit_beacon",
    name="Spirit Beacon",
    abbr="sb",
    mana_type="holy",
    spell_type="utility",
    cast_style="standard",
    allowed_professions=["cleric"],
    min_circle=7,
    min_skill={"primary_magic": 45},
    safe_mana=4,
    mana_min=4,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=35,
    scaling="linear",
    spellbook="Divine Intervention",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    target_type="self",
    min_prep_time=4,
    expiry_window=300,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s04170", "discoverability_state_only"],
    effect_profile={
        "effect_type": "spirit_beacon",
        "utility_behavior": "spirit_beacon",
        "base_duration": 3600,
        "duration_scale": 30.0,
        "capability_flag": "spirit_beacon_active",
        "castmod_a0": 4,
        "castmod_a1": 35,
    },
)

SPELL_REGISTRY["uncurse"] = Spell(
    id="uncurse",
    name="Uncurse",
    abbr="unc",
    mana_type="holy",
    spell_type="utility",
    cast_style="standard",
    allowed_professions=["cleric"],
    min_circle=5,
    min_skill={"primary_magic": 35},
    safe_mana=10,
    mana_min=10,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=51,
    scaling="linear",
    spellbook="Spirit Manipulation",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    target_type="single",
    min_prep_time=5,
    expiry_window=300,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s01976"],
    effect_profile={
        "effect_type": "uncurse",
        "utility_behavior": "uncurse",
        "castmod_a0": 10,
        "castmod_a1": 51,
        "base_curse_power": 10,
        "curse_power_scale": 2.0,
    },
)

SPELL_REGISTRY["hand_of_tenemlor"] = Spell(
    id="hand_of_tenemlor",
    name="Hand of Tenemlor",
    abbr="hot",
    mana_type="holy",
    spell_type="targeted_magic",
    cast_style="targeted",
    allowed_professions=["cleric"],
    min_circle=7,
    min_skill={"primary_magic": 50},
    safe_mana=16,
    mana_min=16,
    mana_max=100,
    diff_per_extra_mana=2,
    base_difficulty=35,
    scaling="linear",
    spellbook="Divine Intervention",
    acquisition_methods=["npc", "player", "book"],
    slot_cost=1,
    target_type="single",
    min_prep_time=7,
    expiry_window=300,
    canon_status="canonical",
    provenance="gsl_2004",
    flags=["script_s07118", "scar_mechanic_deferred"],
    effect_profile={
        "damage_components": [("fire", 1)],
        "damage_location": "left_hand",
        "critical": True,
    },
)

# DRG-CLERIC-02: Grandfathered as project-canonical per DRG-CANON-POLICY-001.
# Existing Cleric-accessible DireEngine roster entry, not 2004-GSL 206xxx content.
SPELL_REGISTRY["shielding"] = Spell(
    id="shielding",
    name="Shielding",
    abbr="sh",
    mana_type="holy",
    spell_type="warding",
    cast_style="standard",
    allowed_professions=list(SPELLCASTING_PROFESSIONS),
    min_circle=1,
    min_skill={"primary_magic": 10},
    safe_mana=10,
    base_difficulty=18,
    scaling="linear",
    spellbook="Fundamentals",
    acquisition_methods=["npc", "player", "book"],
    provenance="directengine_canon",
)

# DRG-CLERIC-02: Grandfathered as project-canonical per DRG-CANON-POLICY-001.
# Existing Cleric-accessible DireEngine roster entry, not 2004-GSL 206xxx content.
SPELL_REGISTRY["flare"] = Spell(
    id="flare",
    name="Flare",
    abbr="fl",
    mana_type="elemental",
    spell_type="targeted_magic",
    cast_style="standard",
    allowed_professions=list(SPELLCASTING_PROFESSIONS),
    min_circle=3,
    min_skill={"primary_magic": 20},
    safe_mana=12,
    base_difficulty=24,
    scaling="linear",
    spellbook="Elemental Targeting",
    acquisition_methods=["npc", "player"],
    provenance="directengine_canon",
)

# DRG-CLERIC-02: Grandfathered as project-canonical per DRG-CANON-POLICY-001.
# Existing Cleric-accessible DireEngine roster entry, not 2004-GSL 206xxx content.
SPELL_REGISTRY["arc_burst"] = Spell(
    id="arc_burst",
    name="Arc Burst",
    abbr="ab",
    mana_type="elemental",
    spell_type="aoe",
    cast_style="room",
    allowed_professions=list(SPELLCASTING_PROFESSIONS),
    min_circle=5,
    min_skill={"primary_magic": 40},
    safe_mana=16,
    base_difficulty=32,
    scaling="linear",
    spellbook="Elemental Targeting",
    acquisition_methods=["npc", "player", "book"],
    target_type="room",
    provenance="directengine_canon",
    effect_profile={
        "max_targets": 5,
        "aoe_scale": "sqrt_split",
    },
)

# DRG-CLERIC-02: Grandfathered as project-canonical per DRG-CANON-POLICY-001.
# Existing Cleric-accessible DireEngine roster entry, not 2004-GSL 206xxx content.
SPELL_REGISTRY["radiant_burst"] = Spell(
    id="radiant_burst",
    name="Radiant Burst",
    abbr="rb",
    mana_type="holy",
    spell_type="aoe",
    cast_style="room",
    allowed_professions=list(SPELLCASTING_PROFESSIONS),
    min_circle=4,
    min_skill={"primary_magic": 30},
    safe_mana=14,
    base_difficulty=30,
    scaling="linear",
    spellbook="Fundamentals",
    acquisition_methods=["npc", "player", "book"],
    target_type="room",
    provenance="directengine_canon",
    effect_profile={
        "max_targets": 5,
        "aoe_scale": "sqrt_split",
    },
)

SPELL_REGISTRY["daze"] = Spell(
    id="daze",
    name="Daze",
    abbr="dz",
    mana_type="lunar",
    spell_type="debilitation",
    cast_style="targeted",
    allowed_professions=["moon_mage"],
    min_circle=4,
    min_skill={"primary_magic": 25},
    safe_mana=14,
    base_difficulty=28,
    scaling="linear",
    spellbook="Psychic Projection",
    acquisition_methods=["npc", "player", "book"],
    effect_profile={
        "effect_type": "daze",
        "base_strength": 1,
        "strength_scale": 0.08,
        "base_duration": 4,
        "duration_scale": 0.5,
        "contest_modifiers": {
            "accuracy": 1.0,
            "evasion": 1.0,
            "magic_attack": 1.0,
            "magic_defense": 1.0,
        },
    },
)

# DRG-CLERIC-02: Grandfathered as project-canonical per DRG-CANON-POLICY-001.
# Existing Cleric-accessible DireEngine roster entry, not 2004-GSL 206xxx content.
SPELL_REGISTRY["hinder"] = Spell(
    id="hinder",
    name="Hinder",
    abbr="hin",
    mana_type="lunar",
    spell_type="debilitation",
    cast_style="targeted",
    allowed_professions=list(SPELLCASTING_PROFESSIONS),
    min_circle=3,
    min_skill={"primary_magic": 20},
    safe_mana=12,
    base_difficulty=24,
    scaling="linear",
    spellbook="Fundamentals",
    acquisition_methods=["npc", "player", "book"],
    provenance="directengine_canon",
    effect_profile={
        "effect_type": "hinder",
        "base_strength": 1,
        "strength_scale": 0.08,
        "base_duration": 4,
        "duration_scale": 0.6,
        "contest_modifiers": {
            "accuracy": 1.0,
            "magic_attack": 1.0,
        },
    },
)

# DRG-CLERIC-02: Grandfathered as project-canonical per DRG-CANON-POLICY-001.
# Existing bespoke DireEngine Cleric spell, not 2004-GSL 206xxx content.
SPELL_REGISTRY["slow"] = Spell(
    id="slow",
    name="Slow",
    abbr="sl",
    mana_type="holy",
    spell_type="debilitation",
    cast_style="targeted",
    allowed_professions=["cleric"],
    min_circle=4,
    min_skill={"primary_magic": 25},
    safe_mana=14,
    base_difficulty=28,
    scaling="linear",
    spellbook="Spirit Manipulation",
    acquisition_methods=["npc", "player", "book"],
    provenance="directengine_canon",
    effect_profile={
        "effect_type": "slow",
        "base_strength": 1,
        "strength_scale": 0.06,
        "base_duration": 5,
        "duration_scale": 0.75,
        "contest_modifiers": {
            "evasion": 1.0,
            "magic_defense": 1.0,
        },
    },
)

# DRG-EMPATH-02 audit classification: canon-compliant.
# Regenerate remains the canonical self-cast Empath cyclic healing seam.
SPELL_REGISTRY["regenerate"] = Spell(
    id="regenerate",
    name="Regenerate",
    abbr="reg",
    mana_type="life",
    spell_type="cyclic",
    cast_style="self",
    allowed_professions=["empath"],
    min_circle=5,
    min_skill={"primary_magic": 35},
    safe_mana=12,
    base_difficulty=30,
    scaling="linear",
    spellbook="Healing",
    acquisition_methods=["npc", "player", "book"],
    effect_profile={
        "target_mode": "self",
        "tick_effect": "healing",
        "tick_scale": 0.18,
        "mana_per_tick_scale": 0.15,
        "interrupt_on_debilitation": True,
    },
)

SPELL_REGISTRY["wither"] = Spell(
    id="wither",
    name="Wither",
    abbr="wth",
    mana_type="lunar",
    spell_type="cyclic",
    cast_style="targeted",
    allowed_professions=["moon_mage"],
    min_circle=5,
    min_skill={"primary_magic": 40},
    safe_mana=14,
    base_difficulty=34,
    scaling="linear",
    spellbook="Psychic Projection",
    acquisition_methods=["npc", "player", "book"],
    effect_profile={
        "target_mode": "single",
        "tick_effect": "damage_over_time",
        "tick_scale": 0.14,
        "mana_per_tick_scale": 0.16,
        "contest_required": True,
        "contest_primary_skill": "debilitation",
        "contest_defense_skill": "warding",
        "contest_defense_stat": "discipline",
        "include_magic_resistance": True,
    },
)

SPELL_REGISTRY["storm_field"] = Spell(
    id="storm_field",
    name="Storm Field",
    abbr="sf",
    mana_type="elemental",
    spell_type="cyclic",
    cast_style="room",
    allowed_professions=["warrior_mage"],
    min_circle=5,
    min_skill={"primary_magic": 40},
    safe_mana=16,
    base_difficulty=36,
    scaling="linear",
    spellbook="Elemental Targeting",
    acquisition_methods=["npc", "player", "book"],
    target_type="room",
    effect_profile={
        "target_mode": "room",
        "tick_effect": "aoe_damage_over_time",
        "tick_scale": 0.14,
        "mana_per_tick_scale": 0.18,
        "max_targets": 5,
    },
)

# DRG-CLERIC-02: Grandfathered as project-canonical per DRG-CANON-POLICY-001.
# Existing Cleric-accessible DireEngine roster entry, not 2004-GSL 206xxx content.
SPELL_REGISTRY["shared_guard"] = Spell(
    id="shared_guard",
    name="Shared Guard",
    abbr="sg",
    mana_type="holy",
    spell_type="warding",
    cast_style="standard",
    allowed_professions=list(SPELLCASTING_PROFESSIONS),
    min_circle=3,
    min_skill={"primary_magic": 25},
    safe_mana=14,
    base_difficulty=26,
    scaling="linear",
    spellbook="Fundamentals",
    acquisition_methods=["npc", "player", "book"],
    target_type="group",
    provenance="directengine_canon",
)

# DRG-CLERIC-02: Grandfathered as project-canonical per DRG-CANON-POLICY-001.
# Existing Cleric-accessible DireEngine roster entry, not 2004-GSL 206xxx content.
SPELL_REGISTRY["glimmer"] = Spell(
    id="glimmer",
    name="Glimmer",
    abbr="gli",
    mana_type="elemental",
    spell_type="utility",
    cast_style="standard",
    allowed_professions=list(SPELLCASTING_PROFESSIONS),
    min_circle=1,
    min_skill={"primary_magic": 10},
    safe_mana=10,
    base_difficulty=16,
    scaling="linear",
    spellbook="Fundamentals",
    acquisition_methods=["npc", "player", "book"],
    provenance="directengine_canon",
    effect_profile={
        "effect_type": "light",
        "base_duration": 20,
        "duration_scale": 1.0,
    },
)

# DRG-CLERIC-02: Grandfathered as project-canonical per DRG-CANON-POLICY-001.
# Existing Cleric-accessible DireEngine roster entry, not 2004-GSL 206xxx content.
SPELL_REGISTRY["cleanse"] = Spell(
    id="cleanse",
    name="Cleanse",
    abbr="cln",
    mana_type="holy",
    spell_type="utility",
    cast_style="standard",
    allowed_professions=list(SPELLCASTING_PROFESSIONS),
    min_circle=3,
    min_skill={"primary_magic": 20},
    safe_mana=12,
    base_difficulty=22,
    scaling="linear",
    spellbook="Fundamentals",
    acquisition_methods=["npc", "player", "book"],
    provenance="directengine_canon",
    effect_profile={
        "effect_type": "cleanse",
    },
)

SPELL_REGISTRY["burden"] = Spell(
    id="burden",
    name="Burden",
    abbr="bur",
    mana_type="lunar",
    spell_type="debilitation",
    cast_style="targeted",
    allowed_professions=list(SPELLCASTING_PROFESSIONS),
    min_circle=1,
    min_skill={"primary_magic": 10},
    safe_mana=12,
    mana_min=1,
    mana_max=30,
    diff_per_extra_mana=2,
    base_difficulty=3,
    scaling="linear",
    spellbook="Analogous Patterns",
    acquisition_methods=["scroll", "book"],
    slot_cost=1,
    apprentice_until_circle=10,
    target_type="single",
    min_prep_time=3,
    expiry_window=180,
    canon_status="canonical",
    provenance="magic_3_0_design",
    effect_profile={
        "effect_type": "burden",
        "base_strength": 2,
        "strength_scale": 0.08,
        "base_duration": 600,
        "duration_scale": 0.0,
        "contest_modifiers": {},
        "stat_debuffs": {"strength": -2},
        "encumbrance_modifier": 5,
        "stacking": "non_stacking",
    },
)

SPELL_REGISTRY["gauge_flow"] = Spell(
    id="gauge_flow",
    name="Gauge Flow",
    abbr="gf",
    mana_type="lunar",
    spell_type="utility",
    cast_style="standard",
    allowed_professions=list(SPELLCASTING_PROFESSIONS),
    min_circle=1,
    min_skill={"primary_magic": 10},
    safe_mana=10,
    mana_min=1,
    mana_max=25,
    diff_per_extra_mana=2,
    base_difficulty=2,
    scaling="linear",
    spellbook="Analogous Patterns",
    acquisition_methods=["scroll", "book"],
    slot_cost=2,
    target_type="self",
    min_prep_time=8,
    expiry_window=300,
    canon_status="canonical",
    provenance="magic_3_0_design",
    effect_profile={
        "effect_type": "gauge_flow",
        "base_duration": 1800,
        "duration_scale": 6.0,
        "utility_behavior": "gauge_flow",
        "capability_flag": "gauge_flow_active",
        "potency_scaling": "research_time_reduction",
    },
)

SPELL_REGISTRY["strange_arrow"] = Spell(
    id="strange_arrow",
    name="Strange Arrow",
    abbr="sa",
    mana_type="lunar",
    spell_type="targeted_magic",
    cast_style="targeted",
    allowed_professions=list(SPELLCASTING_PROFESSIONS),
    min_circle=1,
    min_skill={"primary_magic": 10},
    safe_mana=12,
    mana_min=1,
    mana_max=35,
    diff_per_extra_mana=3,
    base_difficulty=5,
    scaling="linear",
    spellbook="Analogous Patterns",
    acquisition_methods=["scroll", "book"],
    slot_cost=1,
    apprentice_until_circle=10,
    target_type="single",
    min_prep_time=3,
    expiry_window=120,
    canon_status="canonical",
    provenance="magic_3_0_design",
    effect_profile={
        "damage_components": [["puncture", 8], ["electrical", 6]],
        "mana_scaling": "linear",
        "roundtime_seconds": 1,
    },
)

SPELL_REGISTRY["manifest_force"] = Spell(
    id="manifest_force",
    name="Manifest Force",
    abbr="maf",
    mana_type="analogous_patterns",
    spell_type="warding",
    cast_style="standard",
    allowed_professions=list(SPELLCASTING_PROFESSIONS),
    min_circle=1,
    min_skill={"primary_magic": 0},
    safe_mana=12,
    mana_min=1,
    mana_max=30,
    diff_per_extra_mana=3,
    base_difficulty=5,
    scaling="linear",
    spellbook="Analogous Patterns",
    acquisition_methods=["scroll"],
    slot_cost=1,
    apprentice_until_circle=10,
    target_type="self",
    min_prep_time=1,
    expiry_window=600,
    canon_status="canonical",
    provenance="magic_3_0_design",
    effect_profile={
        "absorbs_physical": True,
        "min_capacity": 30,
        "capacity_per_mana": 0.5,
        "base_duration": 600,
        "max_duration": 2400,
        "refresh_behavior": "replace",
        "ward_slot_cost": 1,
    },
)


def get_spell(spell_id: str) -> Spell | None:
    return SPELL_REGISTRY.get(spell_id)