SPELLCASTING_GUILDS = (
    "bard",
    "cleric",
    "empath",
    "moon_mage",
    "necromancer",
    "paladin",
    "ranger",
    "warrior_mage",
)


SPELLS = {
    "flare": {
        "category": "targeted_magic",
        "targeted": True,
        "target_mode": "single",
        "mana_min": 1,
        "mana_max": 20,
        "contest": True,
        "uses_targeting": True,
        "guilds": SPELLCASTING_GUILDS,
        "description": "A compact burst of radiance hurled toward a single foe.",
    },
    "bolster": {
        "category": "augmentation",
        "targeted": False,
        "target_mode": "self",
        "mana_min": 1,
        "mana_max": 20,
        "contest": False,
        "guilds": SPELLCASTING_GUILDS,
        "description": "A simple enhancement that strengthens the caster for a short time.",
    },
    "hinder": {
        "category": "debilitation",
        "targeted": True,
        "target_mode": "single",
        "mana_min": 1,
        "mana_max": 20,
        "contest": True,
        "uses_targeting": True,
        "debuff_type": "accuracy",
        "guilds": SPELLCASTING_GUILDS,
        "description": "A blunt hindering spell that reduces an opponent's effectiveness.",
    },
    "shielding": {
        "category": "warding",
        "targeted": False,
        "target_mode": "self",
        "mana_min": 1,
        "mana_max": 20,
        "contest": False,
        "guilds": SPELLCASTING_GUILDS,
        "description": "A basic ward that forms a temporary magical barrier.",
    },
    "glimmer": {
        "category": "utility",
        "targeted": False,
        "target_mode": "self",
        "mana_min": 1,
        "mana_max": 20,
        "contest": False,
        "guilds": SPELLCASTING_GUILDS,
        "description": "A minor utility spell that surrounds the caster with a soft light.",
    },
    "radiant_aura": {
        "category": "augmentation",
        "targeted": False,
        "target_mode": "self",
        "mana_min": 5,
        "mana_max": 30,
        "contest": False,
        "cyclic": True,
        "guilds": SPELLCASTING_GUILDS,
        "description": "A sustained aura of Radiance that continually reinforces the caster.",
    },
    "radiant_burst": {
        "category": "targeted_magic",
        "targeted": False,
        "target_mode": "room",
        "mana_min": 5,
        "mana_max": 30,
        "contest": True,
        "guilds": SPELLCASTING_GUILDS,
        "description": "A violent bloom of Radiance that lashes out across the room.",
    },
    "shared_guard": {
        "category": "warding",
        "targeted": False,
        "target_mode": "group",
        "mana_min": 5,
        "mana_max": 25,
        "contest": False,
        "guilds": SPELLCASTING_GUILDS,
        "description": "A broad protective field cast over the caster and nearby allies.",
    },
    "cleanse": {
        "category": "utility",
        "targeted": False,
        "target_mode": "self",
        "mana_min": 5,
        "mana_max": 25,
        "contest": False,
        "guilds": SPELLCASTING_GUILDS,
        "description": "A cleansing wash of Radiance that strips away lingering magical effects.",
    },
}